function make_pdf(out_dir,magick_path)

system( [ ...
	'cd ' out_dir ' && ' ...
	magick_path '/convert ' ...
	'connectivity_removegm_noscrub.png ' ...
	'connmatrix_removegm_noscrub.png ' ...
	'connectivity_removegm_scrub.png ' ...
	'connmatrix_removegm_scrub.png ' ...
	'connectivity_keepgm_noscrub.png ' ...
	'connmatrix_keepgm_noscrub.png ' ...
	'connectivity_keepgm_scrub.png ' ...
	'connmatrix_keepgm_scrub.png ' ...
	'coreg_check.png ' ...
	'fmri_conncalc.pdf' ...
	] );
